package lab.arq.hb.geo;
// Generated 25/04/2013 05:04:32 PM by Hibernate Tools 3.2.1.GA



/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private String CId;
     private Pais pais;
     private String CNombre;
     private Integer CHabitantes;

    public Ciudad() {
    }

	
    public Ciudad(String CId) {
        this.CId = CId;
    }
    public Ciudad(String CId, Pais pais, String CNombre, Integer CHabitantes) {
       this.CId = CId;
       this.pais = pais;
       this.CNombre = CNombre;
       this.CHabitantes = CHabitantes;
    }
   
    public String getCId() {
        return this.CId;
    }
    
    public void setCId(String CId) {
        this.CId = CId;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getCNombre() {
        return this.CNombre;
    }
    
    public void setCNombre(String CNombre) {
        this.CNombre = CNombre;
    }
    public Integer getCHabitantes() {
        return this.CHabitantes;
    }
    
    public void setCHabitantes(Integer CHabitantes) {
        this.CHabitantes = CHabitantes;
    }




}


