package lab.arq.hb;
// Generated 2/05/2013 04:30:43 PM by Hibernate Tools 3.2.1.GA



/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private String rut;
     private String nombre;
     private String direccion;

    public Empresas() {
    }

	
    public Empresas(String rut, String direccion) {
        this.rut = rut;
        this.direccion = direccion;
    }
    public Empresas(String rut, String nombre, String direccion) {
       this.rut = rut;
       this.nombre = nombre;
       this.direccion = direccion;
    }
   
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


